name: mulen_pay_sdk
description: A Dart SDK for the Mulen Pay API.
version: 0.0.1
homepage: https://mulenpay.ru/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.0
